### ISSUE TITLE
Bugs when resume from checkpoint file

### ISSUE THREAD

**Issue by Kins1ley** [poodarchu/Det3D#104]
Hi, when I resume from the checkpoint file, I found that it produced erro when called 

_checkpoint = torch.load(filename, map_location=map_location)_

The error is int object is not callable.

Because _map_location_ is calculated in the following code:

_map_location = torch.cuda.current_device()_

and the result is int number.

**Comment by Kins1ley** [comment]
I just changed the code into 

_checkpoint = torch.load(filename, map_location=map_location)_

And it seems no bug.

**Comment by Kins1ley** [comment]
I just changed the code into

checkpoint = torch.load(filename)

And it seems no bug.

**Comment by Kins1ley** [comment]
I just changed the code into

_checkpoint = torch.load(filename)_

And it seems no bug.

**Comment by poodarchu** [comment]
you can try map_location = torch.cuda.device(torch.cuda.current_device())
