### ISSUE TITLE
Cant start training. Floating point exception

### ISSUE THREAD

**Issue by lan-sky** [poodarchu/Det3D#107]
When I train the model in this command:./tools/scripts/train.sh kitti.
I got this BUG:
./tools/scripts/train.sh: line 24: 22795 Floating point exception(core dumped) python3 ./tools/train.py ./examples/point_pillars/configs/kitti_point_pillars_mghead_syncbn.py --work_dir=$PP_WORK_DIR
![image](https://user-images.githubusercontent.com/33541823/83544068-ec04b980-a52f-11ea-90b1-6de3a0cf1a46.png)
I cant solve this problem

**Comment by poodarchu** [comment]
Have you follow the instructions to install Det3D?

**Comment by lan-sky** [comment]
> Have you follow the instructions to install Det3D?

Yes，I follow the instructions.

**Comment by tianweiy** [comment]
what files do you change? This is possible if your point cloud/annotation data are incorrect. For example, I get this once when I accidentally flip the kitti data along the y-axis.

**Comment by lan-sky** [comment]
> what files do you change? This is possible if your point cloud/annotation data are incorrect. For example, I get this once when I accidentally flip the kitti data along the y-axis.

THX，I reinstall the Det3D and solve this problem.
