### ISSUE TITLE
How about kitti performance between multitask and single task?

### ISSUE THREAD

**Issue by Yamin05114** [poodarchu/Det3D#11]
Hi, thanks for your great work!

In the paper and Nuscenes dataset leader board, I saw the remarkable improvements. So how about kitti dataset performance? Did you compare the multitask results with SECOND1.6's single-class results? I think pointpillars multitask is not quite good because it directly uses SECOND1.0 code which failed to choose smartly the headers(even SECOND1.6 is not good). 

Since KITTI dataset exists longer, I believe better results on it will be much persuasive.

Thanks!

**Comment by poodarchu** [comment]
you can run on your own, our model zoo will be published in a few days.
