### ISSUE TITLE
Missing CBGS real augmentation

### ISSUE THREAD

**Issue by MeyLavie** [poodarchu/Det3D#110]
In your paper (CBGS) you show in table 1 sample distribution of training split before and after dataset sampling. At the beginning of training, you have prints that show that although the "before" is identical, the after is far less. Will you publish your real augmentation mechanism, please?

![table1](https://user-images.githubusercontent.com/51787735/83967553-5a989d00-a8cb-11ea-817e-ce4c47a44c73.JPG)
![photo5974148511027016358](https://user-images.githubusercontent.com/51787735/83967607-e7dbf180-a8cb-11ea-95f7-cc0a4f60ecc5.jpg)

**Comment by poodarchu** [comment]
this fig is GT aug, and table 1 is dataset sampling, they are two modules.

**Comment by poodarchu** [comment]
dataset sampling is here: https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/nuscenes/nuscenes.py#L71

**Comment by MeyLavie** [comment]
Thank you @poodarchu for your quick answer,
I'm aware that those are two different modules, but you can see from this table, that since the number of instances and samples "after" the sampling are about 4.5 times larger you can understand that the augmentation module is also involved, isn't it?

I'm looking for the augmentation part that you used to enlarge your data by 4.5 times, the one you mentioned in your article.

**Comment by poodarchu** [comment]
> Thank you @poodarchu for your quick answer,
> I'm aware that those are two different modules, but you can see from this table, that since the number of instances and samples "after" the sampling are about 4.5 times larger you can understand that the augmentation module is also involved, isn't it?
> 
> I'm looking for the augmentation part that you used to enlarge your data by 4.5 times, the one you mentioned in your article.

https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/nuscenes/nuscenes.py#L71

**Comment by poodarchu** [comment]
> Thank you @poodarchu for your quick answer,
> I'm aware that those are two different modules, but you can see from this table, that since the number of instances and samples "after" the sampling are about 4.5 times larger you can understand that the augmentation module is also involved, isn't it?
> 
> I'm looking for the augmentation part that you used to enlarge your data by 4.5 times, the one you mentioned in your article.

dataset is enlarged only due to dataset sampling here: https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/nuscenes/nuscenes.py#L71, it has nothing to do with GT AUG.
