### ISSUE TITLE
Shuffling of KITTI validation examples

### ISSUE THREAD

**Issue by afroowoo** [poodarchu/Det3D#115]
Hi, in the pointpillars kitti config file it seems that the points are not shuffled during validation:

https://github.com/poodarchu/Det3D/blob/255c5937014cf65d5eac3c1066a84d7c719b1ef3/examples/point_pillars/configs/kitti_point_pillars_mghead_syncbn.py#L151-L153

I believe the KITTI pointclouds are organized from far to near, so during voxelization the first 12000 voxels might be filled without exploring the nearby points.

So the question is, is shuffling of KITTI val necessary?

**Comment by tianweiy** [comment]
i think the idea is that you want to get some consistent results for validation. Shuffling will create randomness. Also for kitti 12000 pillars should be fine to cover most of the points.

**Comment by poodarchu** [comment]
> Hi, in the pointpillars kitti config file it seems that the points are not shuffled during validation:
> 
> 
> 
> https://github.com/poodarchu/Det3D/blob/255c5937014cf65d5eac3c1066a84d7c719b1ef3/examples/point_pillars/configs/kitti_point_pillars_mghead_syncbn.py#L151-L153
> 
> 
> 
> I believe the KITTI pointclouds are organized from far to near, so during voxelization the first 12000 voxels might be filled without exploring the nearby points.
> 
> 
> 
> So the question is, is shuffling of KITTI val necessary?

It should be off, and this doesn’t affect the results
