### ISSUE TITLE
How to solve this problem? FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by QYWT** [poodarchu/Det3D#121]
How to solve this problem? 
FileNotFoundError: [Errno 2] No such file or directory: '/media/jsu/F81CA38A1CA3430C/nuScences/NUSCENES_TRAINVAL_DATASET_ROOT/infos_train_10sweeps_withvelo.pkl'

I ran this command ‘python tools/create_data.py nuscenes_data_prep --root_path='/media/jsu/F81CA38A1CA3430C/nuScences/NUSCENES_TRAINVAL_DATASET_ROOT/' --version="v1.0-trainval" --nsweeps=10’。
The error is as follows：
FileNotFoundError: [Errno 2] No such file or directory: '/media/jsu/F81CA38A1CA3430C/nuScences/NUSCENES_TRAINVAL_DATASET_ROOT/infos_train_10sweeps_withvelo.pkl'

**Comment by poodarchu** [comment]
remove quote symbol in root_path='/media/jsu/F81CA38A1CA3430C/nuScences/NUSCENES_TRAINVAL_DATASET_ROOT/'

**Comment by QYWT** [comment]
I have removed the quotes from the command, but the error still exists.
 jsu@214-4:~/Det3D$ python tools/create_data.py nuscenes_data_prep --root_path=/media/jsu/F81CA38A1CA3430C/nuScences/NUSCENES_TRAINVAL_DATASET_ROOT/ --version="v1.0-trainval" --nsweeps=10
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 21.9 seconds.
======
Reverse indexing ...
Done reverse indexing in 6.2 seconds.
======
total scene num: 850
exist scene num: 85
train scene: 62, val scene: 23
100%|█████████████████████████████████████| 34149/34149 [08:26<00:00, 67.38it/s]
train sample: 2462, val sample: 31687
Traceback (most recent call last):
  File "tools/create_data.py", line 40, in <module>
    fire.Fire()
  File "/home/jsu/anaconda3/envs/HRnet/lib/python3.6/site-packages/fire-0.3.1-py3.6.egg/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jsu/anaconda3/envs/HRnet/lib/python3.6/site-packages/fire-0.3.1-py3.6.egg/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/jsu/anaconda3/envs/HRnet/lib/python3.6/site-packages/fire-0.3.1-py3.6.egg/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "tools/create_data.py", line 27, in nuscenes_data_prep
    nsweeps=nsweeps,
  File "/home/jsu/Det3D/det3d/datasets/utils/create_gt_database.py", line 48, in create_groundtruth_database
    nsweeps=kwargs["nsweeps"],
  File "/home/jsu/Det3D/det3d/datasets/nuscenes/nuscenes.py", line 43, in __init__
    root_path, info_path, pipeline, test_mode=test_mode, class_names=class_names
  File "/home/jsu/Det3D/det3d/datasets/custom.py", line 37, in __init__
    self._set_group_flag()
  File "/home/jsu/Det3D/det3d/datasets/custom.py", line 164, in _set_group_flag
    self.flag = np.ones(len(self), dtype=np.uint8)
  File "/home/jsu/Det3D/det3d/datasets/nuscenes/nuscenes.py", line 113, in __len__
    self.load_infos(self._info_path)
  File "/home/jsu/Det3D/det3d/datasets/nuscenes/nuscenes.py", line 68, in load_infos
    with open(self._info_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/jsu/F81CA38A1CA3430C/nuScences/NUSCENES_TRAINVAL_DATASET_ROOT/infos_train_10sweeps_withvelo.pkl'

**Comment by lqzhao** [comment]
@QYWT Same problem, have you solve this problem?

**Comment by tianweiy** [comment]
@lqzhao @QYWT  Change the https://github.com/poodarchu/Det3D/blob/ed0f5418c6c9b06fc5f4b73888703a9a19c2947f/tools/create_data.py#L26 to 
```
        Path(root_path) / "infos_train_{:02d}sweeps_withvelo_filter_True.pkl".format(nsweeps),
```

**Comment by tianweiy** [comment]
@poodarchu  can you fix this? I changed the info name to reflect the filtering.

**Comment by QYWT** [comment]
@tianweiy Thank you for your advice. I have another question, where  and how should I update dataset setting and path?
Update dataset setting and path
dataset_type = "NuScenesDataset"
n_sweeps = 10
data_root = "/data/Datasets/nuScenes"
db_info_path="/data/Datasets/nuScenes/dbinfos_train.pkl"
train_anno = "/data/Datasets/nuScenes/infos_train_10sweeps_withvelo.pkl"
val_anno = "/data/Datasets/nuScenes/infos_val_10sweeps_withvelo.pkl"

**Comment by lqzhao** [comment]
#82 @QYWT

**Comment by poodarchu** [comment]
> @poodarchu can you fix this? I changed the info name to reflect the filtering.

I didn't encounter this error.

**Comment by poodarchu** [comment]
solved.
