### ISSUE TITLE
Question about pillar encoder

### ISSUE THREAD

**Issue by s-ryosky** [poodarchu/Det3D#129]
Why are you disabling cudnn before batch norm?

https://github.com/poodarchu/Det3D/blob/ae5a3ae5a6d1691f5001a87eff72d482fb06265b/det3d/models/readers/pillar_encoder.py#L45-L47

**Comment by poodarchu** [comment]
you can ignore this

**Comment by s-ryosky** [comment]
Thank you for your reply.
Perhaps this is a remnant of using sync BN.
