### ISSUE TITLE
ModuleNotFoundError: No module named 'det3d.ops.nms.nms'

### ISSUE THREAD

**Issue by chowkamlee81** [poodarchu/Det3D#13]
python setup.py develop made an issue

After adding in setup.py, got error below.

det3d/ops/nms/nms_kernel.cu.cc:48:61: note: (if you use \u2018-fpermissive\u2019, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
det3d/ops/nms/nms_kernel.cu.cc:50:61: error: there are no arguments to \u2018min\u2019 that depend on a template parameter, so a declaration of \u2018min\u2019 must be available [-fpermissive]
min(n_boxes - col_start * BLOCK_THREADS, BLOCK_THREADS);
^
det3d/ops/nms/nms_kernel.cu.cc:53:7: error: \u2018threadIdx\u2019 was not declared in this scope
if (threadIdx.x < col_size)
^
det3d/ops/nms/nms_kernel.cu.cc:62:17: error: there are no arguments to \u2018__syncthreads\u2019 that depend on a template parameter, so a declaration of \u2018__syncthreads\u2019 must be available [-fpermissive]
__syncthreads();
^
det3d/ops/nms/nms_kernel.cu.cc:64:7: error: \u2018threadIdx\u2019 was not declared in this scope
if (threadIdx.x < row_size)
^
det3d/ops/nms/nms_kernel.cu.cc: In function \u2018int _nms_gpu(int*, const DType*, int, int, DType, int)\u2019:
det3d/ops/nms/nms_kernel.cu.cc:123:37: error: expected primary-expression before \u2018<\u2019 token
nms_kernel<DType, BLOCK_THREADS><<<blocks, threads>>>(boxes_num,
^
det3d/ops/nms/nms_kernel.cu.cc:123:55: error: expected primary-expression before \u2018>\u2019 token
nms_kernel<DType, BLOCK_THREADS><<<blocks, threads>>>(boxes_num,
^
det3d/ops/nms/nms_kernel.cu.cc: In instantiation of \u2018int _nms_gpu(int*, const DType*, int, int, DType, int) [with DType = float; int BLOCK_THREADS = 64]\u2019:
det3d/ops/nms/nms_kernel.cu.cc:162:65: required from here
det3d/ops/nms/nms_kernel.cu.cc:123:66: warning: left operand of comma operator has no effect [-Wunused-value]
nms_kernel<DType, BLOCK_THREADS><<<blocks, threads>>>(boxes_num,
^
det3d/ops/nms/nms_kernel.cu.cc:124:53: warning: right operand of comma operator has no effect [-Wunused-value]
nms_overlap_thresh,
^
det3d/ops/nms/nms_kernel.cu.cc:125:44: warning: right operand of comma operator has no effect [-Wunused-value]
boxes_dev,
^
det3d/ops/nms/nms_kernel.cu.cc: In instantiation of \u2018int _nms_gpu(int*, const DType*, int, int, DType, int) [with DType = double; int BLOCK_THREADS = 64]\u2019:
det3d/ops/nms/nms_kernel.cu.cc:165:66: required from here
det3d/ops/nms/nms_kernel.cu.cc:123:66: warning: left operand of comma operator has no effect [-Wunused-value]
nms_kernel<DType, BLOCK_THREADS><<<blocks, threads>>>(boxes_num,
^
det3d/ops/nms/nms_kernel.cu.cc:124:53: warning: right operand of comma operator has no effect [-Wunused-value]
nms_overlap_thresh,
^
det3d/ops/nms/nms_kernel.cu.cc:125:44: warning: right operand of comma operator has no effect [-Wunused-value]

boxes_dev,
^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
@chowkamlee81

**Comment by poodarchu** [comment]
you do not need to add nms related stuff into setup.py, you just need to run it twice. Because nms module will be automatically compiled if there's no nms module found. so it will raise not found error during your first time running the repo. So you just need to run the repo again because nms is compiled already.
