### ISSUE TITLE
How Det3D build a model?

### ISSUE THREAD

**Issue by hughlee815** [poodarchu/Det3D#132]
I've been studying this for a long time, but i really cannot understand how Det3D build a model.
i am sure that the model is built by class 'Register', but when i look into the class 'Register', i cannot find any line of code which has contributions to build a Model. 
could you please give any help to clarify the problem?
thanks so much and always waiting for your reply

**Comment by poodarchu** [comment]
https://github.com/poodarchu/Det3D/blob/master/det3d/models/builder.py
