### ISSUE TITLE
Logic behind using sample_groups=[ dict(car=2), dict(truck=3), dict(construction_vehicle=7), dict(bus=4), dict(trailer=6), dict(barrier=2), dict(motorcycle=6), dict(bicycle=6), dict(pedestrian=2), dict(traffic_cone=2), ]

### ISSUE THREAD

**Issue by DeepakVellampalli** [poodarchu/Det3D#134]
## How to use Det3D

Questions like:

1. What is the logic in using values for car=, truck=3 etc for the code line

Det3D/examples/cbgs/configs/nusc_all_vfev3_spmiddleresnetfhd_rpn2_mghead_syncbn.py

**Comment by DeepakVellampalli** [comment]
@poodarchu , could you please help on this logic. Do the needful

**Comment by tojimahammatov** [comment]
hi @DeepakVellampalli , these numbers are magnitudes for each category. The magnitude means number of instances placed into a point could sample. See the paper of cbgs (table 5) for more information.
