### ISSUE TITLE
The bug of rotated IoU calculation in nms_gpu.py

### ISSUE THREAD

**Issue by meng-zha** [poodarchu/Det3D#135]
If the box and the query box are almost  the same,  _rotate_iou_gpu()_ will mistakenly calculate the IoU to be **zero**, which is exactly to be 1. 
The bug occurs in the _inter()_ function at L397 of nms_gpu.py.

**Comment by poodarchu** [comment]
you can add a small vaule like 1e-12 to avoid this.
