### ISSUE TITLE
How to change multi head to single?

### ISSUE THREAD

**Issue by tojimahammatov** [poodarchu/Det3D#137]
## How to change a config file for single head?

Hi, thanks for great work. 

I saw there are three heads available in bbox_heads directory, and I want to train single head with pointpillar (nuscenes). Obviously bbox_head should be replaced in the config, but how about other parameters (tasks, multi_class_nms etc) ?

**Comment by poodarchu** [comment]
you can chang tasks in config to one.

**Comment by tojimahammatov** [comment]
Hi @poodarchu , thanks for your response, and it worked well. By any chance, do you have pre-processing method like SECOND in this repo? (Lidar as well as camera data)
