### ISSUE TITLE
How to train model for a custom object ?

### ISSUE THREAD

**Issue by pra-dan** [poodarchu/Det3D#139]
I am planning to use Det3D to train a detector for a custom object (a toy or some table). I prefer using only RGB. How should I go about it ?  Any starting notes ?
Thanks in advance :)

**Comment by poodarchu** [comment]
Add your datasets by inherit the base Dataset class : https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/custom.py

And specify your image read func and transforms in getitem and configs.
