### ISSUE TITLE
Do you support Waymo? Or how to train Waymo using Det3D?

### ISSUE THREAD

**Issue by HUI11126** [poodarchu/Det3D#144]
Here is an instruction about how to extract the bin file and label file from Waymo.
https://www.jianshu.com/p/a3e8310cea32      (It is written in Chinese.) 

I am a beginner about 3D detection. Could anyone give me a guide to train Waymo using Det3D?

Many thanks.

**Comment by poodarchu** [comment]
Thanks for your interest in Det3D!

It should be quite easy to add a dataset into Det3D. Here are the recommended steps:
1. preprocess the Waymo dataset and generate the infos (annotations) into a pkl file (you can refer to https://github.com/poodarchu/Det3D/blob/master/tools/create_data.py)
2. follow any of existing datasets (e.g. https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/kitti/kitti.py) to create a Waymo(data.datasets) class, and implement the __init__ (which is used to load the infos file generated in step 1) and the __getitem__ (which is used to load the file and preprocess it).
3. Add corresponding evaluation func according to waymo's API and metrics.
