### ISSUE TITLE
How to confirm the matching threshold of anchors

### ISSUE THREAD

**Issue by majaya** [poodarchu/Det3D#147]
I'd like to ask you some questions:
 1. According to the Det3D project settings, the resolution of anchors is 0.8 meters. In this way, for small objects such as pedestrians or Traffic cone(the length and width of pedestrians is about 0.7 meters, and the Traffic cone is about 0.35 meters), is it improper to set 0.6 and 0.4 matching threshold according to the default configuration provided by your NUS example? for example, if the Traffic cone is in the middle of four anchors frames, hypothesis the length and width of the cone is 0.35m, than the matching IOU is less than 0.4. In this way, no anchors can match it, so how to set the matching IOU value in this case? I have set 0.2 and 0.1, but there still some miss In some locations.

2.  In the process of the data preprocessing, it is better to rotate each GT box according to a certain rot noise for training than without this operation. I haven't turned on this operation during training. I want to know if this ops will get better training results. I hope you can give me some suggestions, thanks a lot.

**Comment by poodarchu** [comment]
1. There are actually trade-offs between precision & recall w.r.t. a specific category. If you increase the IoU threshold, the detector might have better precision, while if you decrease the IoU threshold, the detector might tend to detect more proposals w.r.t. that category, and this will also incur many false positives. Actually, you do not need to take all the gts into account, or you can manually set 1 closet anchor to that object.
2. If you're working on a research project, I do not recommend tunning this hyper-parameter, it can be cumbersome, and the gain could also be minor.
