### ISSUE TITLE
Can you shared the results of your reproduced models?

### ISSUE THREAD

**Issue by qiushi223** [poodarchu/Det3D#15]
Dear @poodarchu , 

Thanks for your great work, with your open code, most researchers can save a lot of time. Now, many open source code just cannot reproduce results announced in their papers, which causes much confusion for followers. Can you share detailed results with your reproduced models (like pointrcnn) and give more configs files for various models? Thanks.

**Comment by poodarchu** [comment]
this repo can achieve higher AP than their original papers. It wins nuScenes 3D object detection challenge's 1st place and lyft 3d object detection challenge's 3rd place.
