### ISSUE TITLE
No Module name torch

### ISSUE THREAD

**Issue by Shegun93** [poodarchu/Det3D#153]
while trying to run the setup.py, i got an error no module name torch
![WhatsApp Image 2021-09-21 at 12 48 44 PM](https://user-images.githubusercontent.com/72381301/134165504-bf643493-db71-45ed-878c-3d7808546cd7.jpeg)

**Comment by poodarchu** [comment]
you need to install pytorch before using this repo.

**Comment by Shegun93** [comment]
Hello Benjin,

Thank you for your response. You do not know how glad I am to hear from you.

Can I mail you again for in case I run to another problem on this project

Thanks.
