### ISSUE TITLE
Support PyTorch>1.6

### ISSUE THREAD

**Issue by sidml** [poodarchu/Det3D#154]
As stated in the installation instructions, Det3D library only supports PyTorch 1.1-1.6. Moving forward, users will most likely be using newer versions of torch. So, it may be useful to make the library compatible with newer versions.

Recently when i tried to install the library alongside Pytorch 1.7, I few compilation errors related to the use of AT_CHECK. After resolving it, I was able to compile the library successfully.  If it's okay with you, I can make a PR fixing this error. 
Hopefully after this small change, the library can be used alongside newer versions of Pytorch.

**Comment by poodarchu** [comment]
I've already update the repo to support pytorch 1.7, 1.8 and 1.9.

**Comment by sidml** [comment]
@poodarchu 
Hmm.. I see AT_CHECK still there
https://github.com/poodarchu/Det3D/search?q=AT_CHECK
(I hope I am not missing something obvious )

**Comment by sidml** [comment]
@sissini 
You need to replace AT_CHECK with TORCH_CHECK at all the affected places. The list is here https://github.com/poodarchu/Det3D/search?q=AT_CHECK
@poodarchu I am genuinely curious about why you refuse to fix this issue ?
