### ISSUE TITLE
test.py--OSerror:latest.pth is not a checkpoint file

### ISSUE THREAD

**Issue by gkd2020** [poodarchu/Det3D#156]
Thanks for your code!

## Instructions To Reproduce the Issue:

Traceback (most recent call last):
  File "./tools/test.py", line 214, in <module>
    main()
  File "./tools/test.py", line 172, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/home/zzy/PycharmProjects/Det3D/det3d/torchie/trainer/checkpoint.py", line 155, in load_checkpoint
    raise IOError("{} is not a checkpoint file".format(filename))
OSError: /home/zzy/PycharmProjects/Det3D/work_dirs/latest.pth is not a checkpoint file

1. what changes you made (`git diff`) or what code you wrote
```
test.py not change
```
2. what exact command you run:

python ./tools/test.py --show ./examples/point_pillars/configs/nusc_all_point_pillars_mghead_syncbn.py /home/zzy/PycharmProjects/Det3D/work_dirs/latest.pth

3. what you observed (including the full logs):
```
/home/zzy/miniconda3/envs/det3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_CUDA_DRIVER=/usr/lib/x86_64-linux-gnu/libcuda.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/zzy/miniconda3/envs/det3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
/home/zzy/miniconda3/envs/det3d/lib/python3.6/site-packages/numba/cuda/envvars.py:17: NumbaWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated and consequently ignored, found use of NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice.

For more information about alternatives visit: ('https://numba.pydata.org/numba-doc/latest/cuda/overview.html', '#cudatoolkit-lookup')
  warnings.warn(errors.NumbaWarning(msg))
Traceback (most recent call last):
  File "./tools/test.py", line 214, in <module>
    main()
  File "./tools/test.py", line 172, in main
    checkpoint = load_checkpoint(model, args.checkpoint, map_location="cpu")
  File "/home/zzy/PycharmProjects/Det3D/det3d/torchie/trainer/checkpoint.py", line 155, in load_checkpoint
    raise IOError("{} is not a checkpoint file".format(filename))
OSError: /home/zzy/PycharmProjects/Det3D/work_dirs/latest.pth is not a checkpoint file
```

Neither the model downloaded from the home page nor the model trained by myself can run. Thank you for your help.

**Comment by poodarchu** [comment]
![Screen Shot 2021-11-02 at 3 56 57 PM](https://user-images.githubusercontent.com/11813362/139807484-05fa989a-e4fe-408f-85d2-e1e696621500.png)
does the file exist?

**Comment by gkd2020** [comment]
Thanks a lot ! ! !
The file path is not correct. 
....../work_dirs/nusc_all_point_pillars_mghed_syncbn/latest.pth
