### ISSUE TITLE
No sudo access, local libboost not found

### ISSUE THREAD

**Issue by ajinkyakhoche** [poodarchu/Det3D#159]
I am working on a university server with no sudo access, hence instead of apt-get I used conda to install libboost-dev. Using advise [here](https://github.com/traveller59/spconv/issues/251), I was able to compile spconv successfully. But when i try to build Det3D it's unable to find boost. is there a way to provide a path to boost libs provided by conda to setup.py?
 
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote: None

2. what exact command you run: python setup.py build develop

3. what you observed (including the full logs):
```
Det3D/det3d/ops/nms/nms_cpu.h:9:10: fatal error: boost/geometry.hpp: No such file or directory #include <boost/geometry.hpp> ^~~~~~~~~~~~~~~~~~~~ compilation terminated.
```

**Comment by poodarchu** [comment]
1. sudo apt-get install libboost-all-dev
2. conda install libboost
