### ISSUE TITLE
Strange Results of SECOND on KITTI 

### ISSUE THREAD

**Issue by Son-Goku-gpu** [poodarchu/Det3D#16]
In the training process, the code would eval the trained model every several epoches, while the results were strange like below:
![image](https://user-images.githubusercontent.com/59384638/71612594-71301f00-2bdc-11ea-951d-87efba180c56.png)
How could it be like this?

**Comment by poodarchu** [comment]
how's the final result?

**Comment by Son-Goku-gpu** [comment]
@poodarchu I attached the training log below
[20191231_104437.log](https://github.com/poodarchu/Det3D/files/4012240/20191231_104437.log)

it seems that the model has not converge, with similar loss in different epoches and the same results after each evaluation. I used kitti_car_vfev3_spmiddlefhd_rpn1_mghead_syncbn.py in my training.

**Comment by poodarchu** [comment]
ok, I'll check this.

**Comment by Son-Goku-gpu** [comment]
@poodarchu Thanks! By the way, I have modified the code of line 1038 in /home/zhengwu/code/Det3D-master/det3d/models/bbox_heads/mg_head.py, 
from `) ^dir_labels.byte()` to `) ^ (dir_labels.byte()==1)`
 because the xor operation should have matched data types (bool), otherwise it will throw an exception.

**Comment by Son-Goku-gpu** [comment]
@poodarchu @s-ryosky Thanks for your modification. Now, I can eval the SECOND model trained for about 32 epoches and the evaluation results are shown below:
![捕获](https://user-images.githubusercontent.com/59384638/71709820-3cb6a000-2e34-11ea-960f-fc9969fea625.PNG)
I will check the code later and report any problem if found.
