### ISSUE TITLE
unable to do inference on test set

### ISSUE THREAD

**Issue by GitRooky** [poodarchu/Det3D#163]
When I run  `python tools/dist_test_1.py  /home/leo/research/Det3D/examples/point_pillars/configs/nusc_all_point_pillars_mghead_syncbn.py   --work_dir ./work_dirs/ --checkpoint  /home/leo/research/Det3D/checkpoint/pointpillars/latest.pth --speed_test  --testset`, following errors are raised

[                                                  ] 0/6008, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/dist_test_1.py", line 211, in <module>
    main()
  File "tools/dist_test_1.py", line 157, in main
    for i, data_batch in enumerate(data_loader):
  File "/home/leo/.conda/envs/det3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/leo/.conda/envs/det3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/leo/.conda/envs/det3d/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/leo/.conda/envs/det3d/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/leo/.conda/envs/det3d/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/leo/.conda/envs/det3d/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/leo/.conda/envs/det3d/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/leo/research/Det3D/det3d/datasets/nuscenes/nuscenes.py", line 177, in __getitem__
    return self.get_sensor_data(idx)
  File "/home/leo/research/Det3D/det3d/datasets/nuscenes/nuscenes.py", line 172, in get_sensor_data
    data, _ = self.pipeline(res, info)
  File "/home/leo/research/Det3D/det3d/datasets/pipelines/compose.py", line 23, in __call__
    res, info = t(res, info)
TypeError: cannot unpack non-iterable type object

Can anyone help me fix it ?
@poodarchu @tianweiy @YoushaaMurhij

**Comment by YoushaaMurhij** [comment]
@GitRooky , Can you check the data path in your configs file?

**Comment by GitRooky** [comment]
I have checked them, and they are listed as follows
b_sampler = dict(
    type="GT-AUG",
    enable=False,
    db_info_path="/home/leo/DATA/dataset/nuscenes/trainval/dbinfos_train_10sweeps_withvelo.pkl",
...
_train_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_train_10sweeps_withvelo.pkl"
val_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_val_10sweeps_withvelo.pkl"
test_anno = "/home/leo/DATA/dataset/nuscenes/trainval/v1.0-test/infos_test_10sweeps_withvelo.pkl"_

And my dataset directory is organized as follows

ROOT_NUSC
├── trainval
│   ├── dbinfos_train_10sweeps_withvelo.pkl
│   ├── gt_database_10sweeps_withvelo
│   ├── infos_train_10sweeps_withvelo.pkl
│   ├── infos_val_10sweeps_withvelo.pkl
│   ├── maps
│   ├── samples
│   ├── sweeps
│   ├── v1.0-test
│   ├── v1.0-trainval
│   └── val
└── v1.0-mini
    ├── gt_database
    ├── infos_train.pkl
    ├── infos_val.pkl
    ├── kitti_dbinfos_train.pkl
    ├── maps
    ├── samples
    ├── sweeps
    └── v1.0-mini

**Comment by GitRooky** [comment]
@YoushaaMurhij 
I have checked them, and they are listed as follows
b_sampler = dict(
type="GT-AUG",
enable=False,
db_info_path="/home/leo/DATA/dataset/nuscenes/trainval/dbinfos_train_10sweeps_withvelo.pkl",
...
train_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_train_10sweeps_withvelo.pkl"
val_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_val_10sweeps_withvelo.pkl"
test_anno = "/home/leo/DATA/dataset/nuscenes/trainval/v1.0-test/infos_test_10sweeps_withvelo.pkl"

And my dataset directory is organized as follows

ROOT_NUSC
├── trainval
│   ├── dbinfos_train_10sweeps_withvelo.pkl
│   ├── gt_database_10sweeps_withvelo
│   ├── infos_train_10sweeps_withvelo.pkl
│   ├── infos_val_10sweeps_withvelo.pkl
│   ├── maps
│   ├── samples
│   ├── sweeps
│   ├── v1.0-test
│   ├── v1.0-trainval
│   └── val
└── v1.0-mini
├── gt_database
├── infos_train.pkl
├── infos_val.pkl
├── kitti_dbinfos_train.pkl
├── maps
├── samples
├── sweeps
└── v1.0-mini

**Comment by GitRooky** [comment]
I have checked them, and they are listed as follows
_b_sampler = dict(
type="GT-AUG",
enable=False,
db_info_path="/home/leo/DATA/dataset/nuscenes/trainval/dbinfos_train_10sweeps_withvelo.pkl",_
...
_train_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_train_10sweeps_withvelo.pkl"
val_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_val_10sweeps_withvelo.pkl"
test_anno = "/home/leo/DATA/dataset/nuscenes/trainval/v1.0-test/infos_test_10sweeps_withvelo.pkl"_

And my dataset directory is organized as follows

_ROOT_NUSC
├── trainval
     ├── dbinfos_train_10sweeps_withvelo.pkl
     ├── gt_database_10sweeps_withvelo
     ├── infos_train_10sweeps_withvelo.pkl
     ├── infos_val_10sweeps_withvelo.pkl
     ├── maps
     ├── samples
     ├── sweeps
     ├── v1.0-test
     ├── v1.0-trainval
     └── val_

**Comment by GitRooky** [comment]
> @GitRooky , Can you check the data path in your configs file?

I have checked them, and they are listed as follows
_b_sampler = dict(
type="GT-AUG",
enable=False,
db_info_path="/home/leo/DATA/dataset/nuscenes/trainval/dbinfos_train_10sweeps_withvelo.pkl",
...
train_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_train_10sweeps_withvelo.pkl"
val_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_val_10sweeps_withvelo.pkl"
test_anno = "/home/leo/DATA/dataset/nuscenes/trainval/v1.0-test/infos_test_10sweeps_withvelo.pkl"_

And my dataset directory is organized as follows

_ROOT_NUSC
├── trainval
   ├── dbinfos_train_10sweeps_withvelo.pkl
   ├── gt_database_10sweeps_withvelo│   ├── infos_train_10sweeps_withvelo.pkl
   ├── infos_val_10sweeps_withvelo.pkl
   ├── maps
   ├── samples
   ├── sweeps
   ├── v1.0-test
   ├── v1.0-trainval
   └── val_

**Comment by GitRooky** [comment]
> @GitRooky , Can you check the data path in your configs file?

> @GitRooky , Can you check the data path in your configs file?
@YoushaaMurhij 

**I have checked the data path, and change them. But the same problem still exists. Can you help me out ?**

The data path configurations are listed as follows
_b_sampler = dict(
type="GT-AUG",
enable=False,
db_info_path="/home/leo/DATA/dataset/nuscenes/trainval/dbinfos_train_10sweeps_withvelo.pkl",
...
train_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_train_10sweeps_withvelo.pkl"
val_anno = "/home/leo/DATA/dataset/nuscenes/trainval/infos_val_10sweeps_withvelo.pkl"
test_anno = "/home/leo/DATA/dataset/nuscenes/trainval/v1.0-test/infos_test_10sweeps_withvelo.pkl"_

And my dataset directory is organized as follows

_ROOT_NUSC
├── trainval
   ├── dbinfos_train_10sweeps_withvelo.pkl
   ├── gt_database_10sweeps_withvelo│  
   ├── infos_train_10sweeps_withvelo.pkl
   ├── infos_val_10sweeps_withvelo.pkl
   ├── maps
   ├── samples
   ├── sweeps
   ├── v1.0-test
   ├── v1.0-trainval
   └── val

**Comment by YoushaaMurhij** [comment]
If the paths are correct and the data is prepared correctly, I am not sure what could cause this issue.

**Comment by YoushaaMurhij** [comment]
I see you added testset flag. Are you sure that you prepared it as well?

**Comment by GitRooky** [comment]
> I see you added testset flag. Are you sure that you prepared it as well?

I ran _python tools/create_data.py nuscenes_data_prep --root_path /home/leo/DATA/dataset/nuscenes/trainval//v1.0-test/ --version v1.0-test_, before attempting to inference on the test set.

**Comment by GitRooky** [comment]
> I see you added testset flag. Are you sure that you prepared it as well?

I ran python tools/create_data.py nuscenes_data_prep --root_path /home/leo/DATA/dataset/nuscenes/trainval//v1.0-test/ --version v1.0-test, before attempting to inference on the test set. But I am not sure whether it is correct to prepare the _info.pkl_ file for the test set.

**Comment by GitRooky** [comment]
I have solved the problem by changing the [loading.py of Det3D](https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/pipelines/loading.py) with [loading.py of CenterPoint](https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/pipelines/loading.py)
