### ISSUE TITLE
Gettting error in kitti data preparation

### ISSUE THREAD

**Issue by bhaskar-anand-iith** [poodarchu/Det3D#167]
When I try to prepare kitti data, I get following error:

python create_data.py kitti_data_prep --root_path=/media/bhaskar/Data_Disk/Bhaskar-system_backup/dataset/KITTI_DATASET_ROOT/
Generate info. this may take several minutes.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3712/3712 [00:33<00:00, 111.32it/s]
Kitti info train file is saved to /media/bhaskar/Data_Disk/Bhaskar-system_backup/dataset/KITTI_DATASET_ROOT/kitti_infos_train.pkl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3769/3769 [00:33<00:00, 112.87it/s]
Kitti info val file is saved to /media/bhaskar/Data_Disk/Bhaskar-system_backup/dataset/KITTI_DATASET_ROOT/kitti_infos_val.pkl
Kitti info trainval file is saved to /media/bhaskar/Data_Disk/Bhaskar-system_backup/dataset/KITTI_DATASET_ROOT/kitti_infos_trainval.pkl
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7518/7518 [01:05<00:00, 114.86it/s]
Kitti info test file is saved to /media/bhaskar/Data_Disk/Bhaskar-system_backup/dataset/KITTI_DATASET_ROOT/kitti_infos_test.pkl
  0%|                                                                                                                                                                     | 1/3712 [00:00<00:19, 190.18it/s]
Traceback (most recent call last):
  File "create_data.py", line 40, in <module>
    fire.Fire()
  File "/media/bhaskar/Data_Disk/object_detection/ssdenv/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/media/bhaskar/Data_Disk/object_detection/ssdenv/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/media/bhaskar/Data_Disk/object_detection/ssdenv/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "create_data.py", line 15, in kitti_data_prep
    kitti_ds.create_reduced_point_cloud(root_path)
  File "/media/bhaskar/Data_Disk/object_detection/SE-SSD/Det3D/det3d/datasets/kitti/kitti_common.py", line 207, in create_reduced_point_cloud
    _create_reduced_point_cloud(data_path, train_info_path, save_path)
  File "/media/bhaskar/Data_Disk/object_detection/SE-SSD/Det3D/det3d/datasets/kitti/kitti_common.py", line 177, in _create_reduced_point_cloud
    Path.mkdir(v_path.parent.parent / (v_path.parent.stem + "_reduced"))
  File "/usr/lib/python3.7/pathlib.py", line 1258, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/media/bhaskar/Data_Disk/Bhaskar-system_backup/dataset/KITTI_DATASET_ROOT/training/velodyne_reduced'

**Comment by sixcomicpen** [comment]
I have the same problem. Have you solved it

**Comment by sixcomicpen** [comment]
you can add "parents=True,exist_ok=True" into Det3D-master/det3d/datasets/kitti/kitti_common.py 179,like: Path.mkdir(v_path.parent.parent / (v_path.parent.stem + "_reduced"),parents=True,exist_ok=True)

**Comment by bhaskar-anand-iith** [comment]
> 

Ok let me try it..

**Comment by bhaskar-anand-iith** [comment]
Yes, it is working. Thanks a lot!
