### ISSUE TITLE
Why does the pointpillars net not have voxelization operation at the beginning?

### ISSUE THREAD

**Issue by chenrui17** [poodarchu/Det3D#169]
I am a begginer of 3D obejct detection, i compared some pointpillars relization from det3d , mmdetection3D and PointPillars(https://github.com/zhulf0804), such as:

mmdetection3d : **voxelization** -> PillarFeatureNet -> PointPillarsScatter -> SECONDFPN -> Anchor3DHead
det3d: PillarFeatureNet -> PointPillarsScatter -> RPN -> MultiGroupHead
PointPillars : **voxelization** -> PillarEncoder -> backbone...

and i found mmdetection3D repo's pointpillars net and paper's PointPillars both have **voxelization** operation,  but det3d's pointpillars net is not. why ?

**Comment by poodarchu** [comment]
https://github.com/poodarchu/Det3D/blob/master/examples/point_pillars/configs/nusc_all_point_pillars_mghead_syncbn.py#L275
