### ISSUE TITLE
Training with Multi-GPU

### ISSUE THREAD

**Issue by peiyunh** [poodarchu/Det3D#23]
Hi, 

Thanks for sharing your great work! I am wondering if it is easy to train with multiple GPUs. I tried calling `tools/train.py` with `--gpus=4` but it does not seem to do the trick.

Thanks, 
Peiyun

**Comment by peiyunh** [comment]
According to the README, there seems to be a way that one can train in a distributed manner, but I haven't figured out how to do that. I'd appreciate it if someone could help me on this. Thanks.

**Comment by poodarchu** [comment]
training using multi gpu is very fast in Det3D.
It only take 2 hours to train KITTI, even for nuScenes dataset, it only need less than 2 days.

you can look at this shell script.
https://github.com/poodarchu/Det3D/blob/master/tools/scripts/train.sh

**Comment by peiyunh** [comment]
Works like a charm. Thanks!
