### ISSUE TITLE
can you please provide the code to generate road plane for each dataset?

### ISSUE THREAD

**Issue by qchenclaire** [poodarchu/Det3D#24]
Or just provide the estimated plane files. Thanks!

**Comment by poodarchu** [comment]
https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/utils/ground_plane_detection.py

**Comment by qchenclaire** [comment]
@poodarchu for KITTI, the format is path_to_kitti/training/planes/*.txt with one line denoting "A B C D"?

**Comment by abhigoku10** [comment]
@qchenclaire @poodarchu  are we doing ground plan estimation for KITTI data or passing the planes to the training . i wanted to estimate the ground plan for the give set of data can i do using that code

**Comment by qchenclaire** [comment]
> @qchenclaire @poodarchu are we doing ground plan estimation for KITTI data or passing the planes to the training . i wanted to estimate the ground plan for the give set of data can i do using that code

The code requires getting road planes for KITTI, but planes/*.txt is not provided. The code to directly generate these files is not provided(as far as I know), but we can adapt that from Nuscenes

**Comment by qchenclaire** [comment]
> @qchenclaire @poodarchu are we doing ground plan estimation for KITTI data or passing the planes to the training . i wanted to estimate the ground plan for the give set of data can i do using that code

if you set with_gp=False, you won't be doing ground plan estimation for kitti
