### ISSUE TITLE
Ground truth velocities are left uninitialized as NaNs

### ISSUE THREAD

**Issue by peiyunh** [poodarchu/Det3D#46]
I believe this is related to #6 #42 #43 and #19 . 

I followed INSTALL.md and installed nuscenes from https://github.com/poodarchu/nuscenes.git. I have also run `create_data.py` accordingly. From what I have seen, ground truth velocities that are cached in `infos_train_10sweeps_withvelo.pkl` are all NaN. I believe this is at least one of the issues that results in NaN losses. 

I think [line 516 in `nusc_common.py`](https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/nuscenes/nusc_common.py#L516) 
```
velocity = np.array([b.velocity for b in ref_boxes]).reshape(-1, 3)
```
should be: 
```
velocity = np.array([
    nusc.box_velocity(token) for token in sample['anns']
]).reshape((-1, 3))
```

Otherwise the function (`box_velocity`) that computes velocity will never be called and `b.velocity` will stay uninitialized as NaNs.

**Comment by peiyunh** [comment]
Closing this issue as it `b.velocity` is no longer NaN once I properly installed the customized nuscenes.

**Comment by muzi2045** [comment]
the author use the their fork version of nuscens-devkit.
you can just modify this file ~/.local/lib/python3.6/site-packages/nuscenes/nuscenes.py
```
# Cannot estimate velocity for a single annotation.
if not has_prev and not has_next:
     return np.array([0.0, 0.0, 0.0])
```
```
if time_diff > max_time_diff:
    # If time_diff is too big, don't return an estimate.
    return np.array([0.0, 0.0, 0.0])
else:
    return pos_diff / time_diff
```

**Comment by peiyunh** [comment]
Interesting. Thanks for pointing this out!

**Comment by hz3014** [comment]
> Closing this issue as `b.velocity` are no longer NaNs once I properly installed the customized nuscenes.

Hi, I have both official and customized nuscenes devkit installed. How do you make sure that the customized version is used?

**Comment by peiyunh** [comment]
I think the easiest way is to create a virtual environment with only the customized devkit installed.
