### ISSUE TITLE
the nms op module has no correspond compiled scripts

### ISSUE THREAD

**Issue by muzi2045** [poodarchu/Det3D#5]
I have try to use 
`python3 setup.py build develop`
it looks like the nms.so can't be generated in this repo, the other ops can be normally compiled.

**Comment by poodarchu** [comment]
nms.so will be automatically compiled on the first run. so you just need to run it twice and the module will be ready to be used.

**Comment by muzi2045** [comment]
there is nothing about nms op module in the setup.py or CMakeLists.txt , how could it be auto compiled？
I have add this in the setup.py, and it can be compiled.
```
CUDAExtension(
                name="det3d.ops.nms.nms",
                sources=[
                    "det3d/ops/nms/nms.cc",
                    # "det3d/ops/nms/nms.h",
                    "det3d/ops/nms/nms_kernel.cu",
                    # "det3d/ops/nms/nms_cpu.h",
                ],
                extra_compile_args={"cxx": ["-g"], "nvcc": ["-O2"]},
            ),
```
Maybe you can try cloned this repo into a new machine and run it from scratch.
@poodarchu
