### ISSUE TITLE
where is code for dataset sampling(DS Sampling)?

### ISSUE THREAD

**Issue by turboxin** [poodarchu/Det3D#50]
hi, thanks for this great code base.
I wonder where is code for dataset sampling(DS Sampling), which cause +5 map gain according to your paper "Class-balanced Grouping and Sampling for Point Cloud 3D Object Detection", I could only find db_sampler of "GT_AUG" type, but I think it's diffierent than DS Sampling, am I understanding this correctly?

**Comment by buaaJeremyduan** [comment]
I think is in nuscenes.py load_infos

**Comment by poodarchu** [comment]
please use issue template

**Comment by turboxin** [comment]
@buaaJeremyduan  thanks for clarifying that for me!
