### ISSUE TITLE
error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

### ISSUE THREAD

**Issue by cslxiao** [poodarchu/Det3D#51]
I encounter this error when executing
```bash
python setup.py build develop
```
---
det3d/ops/sigmoid_focal_loss/src/sigmoid_focal_loss_cuda.cu(121): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"
---

**Comment by a157801** [comment]
> I encounter this error when executing
> 
> ```shell
> python setup.py build develop
> ```
> 
> ## det3d/ops/sigmoid_focal_loss/src/sigmoid_focal_loss_cuda.cu(121): error: no suitable constructor exists to convert from "c10::ScalarType" to "at::Type"

Please check the version of cuda cudnn and gcc. I use gcc 5.4.0.

**Comment by poodarchu** [comment]
you need to use gpu to compile. or it will raise error when executing. Please follow instructions.

**Comment by cslxiao** [comment]
I use cuda 10, cudnn 7.5 and gcc 7.4.
I strictly followed the instructions but still got the error

**Comment by a157801** [comment]
> I use cuda 10, cudnn 7.5 and gcc 7.4.
> I strictly followed the instructions but still got the error

Please use gcc 5.4.0 and try again

**Comment by muzi2045** [comment]
If you are using pytorch 1.0, you will face this error(same as me).
there is some api changed between torch 1.0 and 1.3

**Comment by cslxiao** [comment]
@muzi2045 Thanks. Updating torch solves this problem.
