### ISSUE TITLE
Waymo dataset support

### ISSUE THREAD

**Issue by fcakyon** [poodarchu/Det3D#52]
First of all, thanks a lot for this comprehensive 3d detection library!

Considering [open waymo dataset](https://github.com/waymo-research/waymo-open-dataset) has 10x more annotations compared to nuscenes, do you have any intention of adding [open waymo dataset](https://github.com/waymo-research/waymo-open-dataset) support?

**Comment by poodarchu** [comment]
I do not have time to do this, are you interested in add waymo support?
