### ISSUE TITLE
Not support pytorch 1.1

### ISSUE THREAD

**Issue by s-ryosky** [poodarchu/Det3D#53]
## Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
After the commit b567905d961bad4eef3fcfd2bc8253826a882536

2. what exact command you run:
Det3D/tools/train.py

3. what you observed (including the full logs):
```
AttributeError: 'Tensor' object has no attribute 'bool'
```
is occurred in the following line.
https://github.com/poodarchu/Det3D/blob/56402d4761a5b73acd23080f537599b0888cce07/det3d/models/bbox_heads/mg_head.py#L1038

4. please also simplify the steps as much as possible so they do not require additional resources to
Run on PyTorch 1.1

## Expected behavior:
PyTorch 1.1 or higher is recommended in readme.
But PyTorch==1.1 doesn't support to the 'bool' attribute.

**Comment by poodarchu** [comment]
dir_labels.byte()
