### ISSUE TITLE
Error in nuscenes-devkit installation

### ISSUE THREAD

**Issue by nyg2017** [poodarchu/Det3D#54]
Error when I install the nuscenes-devkit. 
The detail error is :
error in nuscenes-zbj setup command: "values of 'package_data' dict" must be a list of strings (got '*.json')

**Comment by poodarchu** [comment]
python setup.py install

**Comment by nyg2017** [comment]
> python setup.py install
Thx for your reply.
I runed this cmd, but the error just like that.

**Comment by nyg2017** [comment]
> python setup.py install

did I need download the dataset before I install the nuscenes-devkit？

**Comment by poodarchu** [comment]
or you can try python setup.py build develop;
if it doesn't work, plean pip uninstall nuscenes_zbj and re clone again.

**Comment by muzi2045** [comment]
"values of 'package_data' dict" must be a list of strings (got '*.json') when installing nuscenes-devikit
Use setuptools 39.1.0

**Comment by nyg2017** [comment]
> "values of 'package_data' dict" must be a list of strings (got '*.json') when installing nuscenes-devikit
> Use setuptools 39.1.0

did you slove this problem?

**Comment by a157801** [comment]
you just need to install setuptools  39.1.0 as claimed in install.md
