### ISSUE TITLE
Where can I download sample dataset

### ISSUE THREAD

**Issue by chenshida** [poodarchu/Det3D#56]
## Where can I download sample dataset

I want to run you sample code, but I dou`t know where can I download this dataset. Can you support the dataset download link?

**Comment by poodarchu** [comment]
which one?

**Comment by chenshida** [comment]
KITTI Dataset, but I would like all of then

**Comment by poodarchu** [comment]
> KITTI Dataset, but I would like all of then

do you know how to use google?
please don't ask unrelated questions.
