### ISSUE TITLE
How to classify multi-class using PointPillar in kitti dataset？

### ISSUE THREAD

**Issue by smell-fishy** [poodarchu/Det3D#65]
Hi，
Is there any pointpillar model or model configure for multiclass detection in kitti dataset？

**Comment by poodarchu** [comment]
you can reference nuscenes configs. You just need to modify multi task configs.

**Comment by smell-fishy** [comment]
> you can reference nuscenes configs. You just need to modify multi task configs.

Thanks! I will try it.
