### ISSUE TITLE
Augmentation , Class group balancing and Anchors

### ISSUE THREAD

**Issue by abhigoku10** [poodarchu/Det3D#7]
@poodarchu @a157801  thanks for the wonderful code base had few queries 
1. as mentioned in the paper which function performs the GT-AUG in the current code base 
2.Is class group balancing feature performed in the current code base if so which function is performing 
3. are anchors generated separately for kitti and nuscenses or having the same anchor which performs the anchor generation

**Comment by poodarchu** [comment]
1. db sampler is used to do GT-AUG.
2. you can check nuscenes.py's __init__ function.
3. anchors of KITTI or nuScenes or Lyft use different configurations.

**Comment by poodarchu** [comment]
1. db sampler is used to do GT-AUG.
2. you can check nuscenes.py's __init__ function.
3. anchors of KITTI or nuScenes or Lyft use different configurations.

**Comment by abhigoku10** [comment]
@poodarchu  can i view the augmented data or save it to see how the augmentation is working

**Comment by s-ryosky** [comment]
Hi @abhigoku10 
The augmented data will not be saved because the augmentation is processed online while training.
But the cropped points in the GT boxes for GT-AUG will be saved in gt_database folder.
Please make a code to visualize how the augmentation is working.

**Comment by poodarchu** [comment]
> @poodarchu can i view the augmented data or save it to see how the augmentation is working

If you need to visualize data / feature map or anything else, you can use scripts in det3d/visualization
