### ISSUE TITLE
求助求助

### ISSUE THREAD

**Issue by huizhilei** [poodarchu/Det3D#70]
How to determine in which direction a certain annotation was taken by the camera？
您好。
我是在读本科生，关于nuscenes可以交流一下吗？
想问一下，对于某个sample，其有6个方向的camera的jpg图片
现在我们想要确定某个方向图片的annotation。
可是，官方接口只给出了一个sample的所有annotation，这包括六个方向所有图片的annotation，我们无法确定某个方向图片有哪些annotation与之对应。
拜托了， 麻烦了。

也就是，怎么知道 某个annotation是哪个方向的相机拍出来的
How to determine in which direction a certain annotation was taken by the camera？

**Comment by poodarchu** [comment]
you should ask nuScenes for help.
