### ISSUE TITLE
ModuleNotFoundError: No module named 'det3d' when running create_data.py

### ISSUE THREAD

**Issue by ilopezfr** [poodarchu/Det3D#72]
I'm following the instructions in GETTING_STARTED.md. 

When running from Det3D directory: 
```
python tools/create_data.py kitti_data_prep --root_path=KITTI_DATASET_ROOT
```

I'm getting the following error: 
```
Traceback (most recent call last):
  File "tools/create_data.py", line 10, in <module>
    from det3d.datasets.kitti import kitti_common as kitti_ds
ModuleNotFoundError: No module named 'det3d'
```
Does anyone else have found the same issue?

**Comment by tianweiy** [comment]
that seems just a python path problem. if other things don't work, probably just try to add the path directly using sys library?

**Comment by MeyLavie** [comment]
Also, make sure that the build step (setup.py) was done successfully.
