### ISSUE TITLE
error in nuscenes-zbj setup command: "values of 'package_data' dict" must be a list of strings (got '*.json')

### ISSUE THREAD

**Issue by athulvingt** [poodarchu/Det3D#77]
got this error  "error in nuscenes-zbj setup command: "values of 'package_data' dict" must be a list of strings (got '*.json')"

how to esolve this

**Comment by tianweiy** [comment]
You can either update the script(add a [] outside of the .json to make it a list) or downgrade your setuptools lib

**Comment by tianweiy** [comment]
https://github.com/poodarchu/Det3D/blob/master/INSTALLATION.md#values-of-package_data-dict-must-be-a-list-of-strings-got-json-when-installing-nuscenes-devikit
