### ISSUE TITLE
Pre Trained models release 

### ISSUE THREAD

**Issue by mzahran001** [poodarchu/Det3D#79]
## Feature

Can you release a pre-trained model for every architecture you release?
## Motivation

It is obvious that your library is becoming the standard framework for 3D object detection and it will be beneficial for the community if you can release the pre-trained models

**Comment by KSaikishore** [comment]
> ## Feature
> Can you release a pre-trained model for every architecture you release?
> 
> ## Motivation
> It is obvious that your library is becoming the standard framework for 3D object detection and it will be beneficial for the community if you can release the pre-trained models

hii @mzahran001 please do reply if you have the pretrained model

**Comment by poodarchu** [comment]
https://github.com/poodarchu/Det3D/blob/master/examples/cbgs/README.md
I've already released pre-trained model long time ago.
