### ISSUE TITLE
DDP consumes much more GPU memory

### ISSUE THREAD

**Issue by turboxin** [poodarchu/Det3D#8]
@poodarchu @a157801 thanks for this wonderful code base. 
When training pointpillars on one gpu(3 samples per gpu),  it consumes 8417MB GPU memory.
However, it consumes 13849/13237 MB memory when trained on 2 gpus in one machine with DDP, and samples per gpu are still 3.
I wonder if this normal case?

**Comment by poodarchu** [comment]
when using DDP, GPU 0 will cost slightly more memory than other GPUs.  But 8400 -> 13800 seems to be abnormal. Please make a merge request if you find any bug.

**Comment by turboxin** [comment]
Will report if finding any bug~
I also wondering what DistOptimizerHook, specifically allreduce_grads are for? Isnt't this automatically done by torch.nn.parallel.DDP?
And after disabling DistOptimizerHook, the gpu memory grows from 13849/13237 MB to 15643/19215 MB with DDP, which is even weirder

**Comment by turboxin** [comment]
Please correct me if I'm wrong~

**Comment by poodarchu** [comment]
DistOptimizerHook just perform clip gard only: https://github.com/poodarchu/Det3D/blob/5ea989d0d275a5ea3d65d30f7bc885c6e73adbbe/det3d/torchie/trainer/hooks/optimizer.py#L15

**Comment by turboxin** [comment]
Sorry but your link is OptimizerHook,  DistOptimizerHook additionally performs allreduce_grads:[https://github.com/poodarchu/Det3D/blob/5ea989d0d275a5ea3d65d30f7bc885c6e73adbbe/det3d/core/utils/dist_utils.py#L31](url)

**Comment by poodarchu** [comment]
it does the same thing.
