### ISSUE TITLE
which config file match the Trained Model named model_epoch_025_step_100100.pth

### ISSUE THREAD

**Issue by 008yheng** [poodarchu/Det3D#80]
there are two config file in the dir Det3D/examples/cbgs/configs  lyft*.py and nusc*.py
when I load the model with the file nusc ,the the model unable get right result and as fllow

The model and loaded state dict do not match exactly

unexpected key in source state_dict: model, optimizer, iteration, epoch

missing keys in source state_dict: backbone.middle_conv.8.bn1.running_var, backbone.middle_conv.3.bn2.running_mean, neck.blocks.0.17.bias, backbone.middle_conv.19.bn2.running_mean, backbone.middle_conv.1.running_mean, bbox_head.tasks.2.conv_dir.weight, backbone.middle_conv.4.conv2.bias, backbone.middle_conv.4.conv1.bias, backbone.middle_conv.11.running_mean, backbone.middle_conv.13.conv1.bias, backbone.middle_conv.4.conv2.weight, backbone.middle_conv.1.weight, neck.blocks.0.13.weight, bbox_head.tasks.2.conv_dir.bias, backbone.middle_conv.14.bn1.weight, backbone.middle_conv.5.weight, backbone.middle_conv.6.running_var, backbone.middle_conv.8.conv2.bias, neck.blocks.0.5.weight, backbone.middle_conv.14.bn2.running_mean, backbone.middle_conv.1.bias, backbone.middle_conv.9.bn1.bias, backbone.middle_conv.14.bn2.running_var, backbone.middle_conv.18.bn2.weight, backbone.middle_conv.8.bn1.bias, bbox_head.tasks.3.conv_cls.bias, backbone.middle_conv.16.running_var, backbone.middle_conv.18.bn1.weight, backbone.middle_conv.18.conv1.bias, neck.blocks.1.17.bias, backbone.middle_conv.6.weight, bbox_head.tasks.3.conv_dir.weight, backbone.middle_conv.11.weight, backbone.middle_conv.8.conv1.weight, neck.blocks.0.2.running_mean, backbone.middle_conv.9.conv1.weight, bbox_head.tasks.4.conv_cls.weight, neck.deblocks.0.1.weight, neck.blocks.1.2.running_var, neck.blocks.0.8.bias, backbone.middle_conv.13.bn1.bias, backbone.middle_conv.4.bn2.weight, neck.deblocks.0.1.running_var, backbone.middle_conv.19.bn2.weight, bbox_head.tasks.3.conv_dir.bias, backbone.middle_conv.14.bn2.weight, neck.blocks.1.14.weight, neck.blocks.1.11.weight, backbone.middle_conv.9.conv2.weight, backbone.middle_conv.18.bn2.running_mean, neck.blocks.0.5.running_mean, backbone.middle_conv.3.bn1.bias, neck.deblocks.0.1.running_mean, bbox_head.tasks.1.conv_dir.weight, bbox_head.tasks.5.conv_box.bias, bbox_head.tasks.0.conv_box.weight, backbone.middle_conv.3.bn1.running_mean, neck.blocks.1.8.weight, backbone.middle_conv.4.bn2.bias, neck.blocks.1.8.running_var, neck.blocks.1.2.bias, bbox_head.tasks.0.conv_box.bias, backbone.middle_conv.4.bn1.running_mean, backbone.middle_conv.10.weight, neck.blocks.1.17.running_var, neck.deblocks.1.1.bias, backbone.middle_conv.3.bn1.weight, backbone.middle_conv.9.bn2.weight, bbox_head.tasks.5.conv_dir.bias, backbone.middle_conv.8.bn1.weight, neck.deblocks.1.0.weight, backbone.middle_conv.4.bn2.running_mean, neck.blocks.1.5.bias, backbone.middle_conv.13.bn1.running_var, bbox_head.tasks.4.conv_box.weight, backbone.middle_conv.8.bn2.running_var, neck.blocks.1.2.weight, backbone.middle_conv.11.bias, neck.blocks.1.5.running_var, backbone.middle_conv.19.conv1.bias, backbone.middle_conv.1.running_var, bbox_head.tasks.2.conv_cls.weight, neck.blocks.0.2.weight, backbone.middle_conv.9.bn2.bias, backbone.middle_conv.9.bn1.running_mean, backbone.middle_conv.21.weight, neck.blocks.1.17.running_mean, backbone.middle_conv.8.bn1.running_mean, backbone.middle_conv.13.bn1.weight, bbox_head.tasks.2.conv_cls.bias, backbone.middle_conv.14.bn1.bias, neck.blocks.0.2.bias, neck.blocks.1.16.weight, bbox_head.tasks.5.conv_dir.weight, neck.blocks.1.10.weight, bbox_head.tasks.0.conv_cls.weight, neck.blocks.1.5.weight, bbox_head.tasks.3.conv_box.bias, backbone.middle_conv.14.conv1.weight, backbone.middle_conv.19.bn1.weight, neck.blocks.0.17.running_mean, bbox_head.tasks.4.conv_box.bias, neck.blocks.0.11.bias, neck.blocks.0.17.weight, backbone.middle_conv.3.bn2.running_var, bbox_head.tasks.3.conv_cls.weight, backbone.middle_conv.0.weight, backbone.middle_conv.18.conv1.weight, backbone.middle_conv.18.bn2.running_var, backbone.middle_conv.9.conv1.bias, neck.deblocks.1.1.weight, bbox_head.tasks.1.conv_cls.bias, bbox_head.tasks.3.conv_box.weight, backbone.middle_conv.4.bn2.running_var, neck.blocks.0.5.running_var, backbone.middle_conv.9.conv2.bias, backbone.middle_conv.4.bn1.weight, neck.blocks.0.5.bias, neck.blocks.1.1.weight, backbone.middle_conv.21.bias, backbone.middle_conv.14.conv1.bias, backbone.middle_conv.8.conv1.bias, backbone.middle_conv.6.running_mean, backbone.middle_conv.13.conv1.weight, backbone.middle_conv.9.bn2.running_var, neck.blocks.1.5.running_mean, neck.blocks.0.11.weight, bbox_head.tasks.4.conv_dir.weight, neck.blocks.1.14.running_var, neck.deblocks.0.1.bias, bbox_head.tasks.2.conv_box.bias, backbone.middle_conv.4.conv1.weight, backbone.middle_conv.19.bn2.bias, neck.blocks.0.11.running_mean, neck.blocks.0.11.running_var, backbone.middle_conv.8.bn2.bias, backbone.middle_conv.19.bn2.running_var, backbone.middle_conv.13.bn2.bias, backbone.middle_conv.8.conv2.weight, neck.blocks.1.14.running_mean, backbone.middle_conv.3.bn2.bias, backbone.middle_conv.18.bn2.bias, backbone.middle_conv.18.bn1.running_var, bbox_head.tasks.0.conv_dir.bias, neck.blocks.1.4.weight, backbone.middle_conv.14.conv2.bias, neck.blocks.0.16.weight, neck.blocks.0.8.weight, backbone.middle_conv.13.bn2.weight, neck.blocks.0.14.running_var, neck.deblocks.0.0.weight, neck.deblocks.1.1.running_var, backbone.middle_conv.13.conv2.bias, neck.blocks.1.11.bias, backbone.middle_conv.13.conv2.weight, neck.blocks.0.17.running_var, backbone.middle_conv.19.bn1.running_mean, neck.blocks.0.14.bias, backbone.middle_conv.3.conv1.bias, backbone.middle_conv.18.bn1.bias, neck.blocks.0.8.running_var, backbone.middle_conv.13.bn1.running_mean, bbox_head.tasks.4.conv_cls.bias, neck.blocks.1.17.weight, neck.blocks.1.14.bias, backbone.middle_conv.14.bn2.bias, bbox_head.tasks.2.conv_box.weight, backbone.middle_conv.18.conv2.weight, backbone.middle_conv.9.bn1.running_var, backbone.middle_conv.3.bn2.weight, bbox_head.tasks.1.conv_box.weight, bbox_head.tasks.0.conv_cls.bias, backbone.middle_conv.19.conv1.weight, backbone.middle_conv.8.bn2.weight, neck.blocks.1.8.bias, bbox_head.tasks.0.conv_dir.weight, bbox_head.tasks.1.conv_cls.weight, bbox_head.tasks.1.conv_box.bias, bbox_head.tasks.4.conv_dir.bias, bbox_head.tasks.5.conv_cls.bias, neck.blocks.1.7.weight, backbone.middle_conv.19.conv2.weight, backbone.middle_conv.3.conv2.weight, neck.blocks.1.2.running_mean, backbone.middle_conv.14.conv2.weight, backbone.middle_conv.20.weight, neck.blocks.1.11.running_var, backbone.middle_conv.16.running_mean, backbone.middle_conv.16.bias, neck.blocks.0.1.weight, backbone.middle_conv.18.conv2.bias, backbone.middle_conv.6.bias, neck.blocks.1.11.running_mean, backbone.middle_conv.21.running_var, neck.blocks.0.2.running_var, backbone.middle_conv.4.bn1.bias, backbone.middle_conv.8.bn2.running_mean, backbone.middle_conv.14.bn1.running_mean, backbone.middle_conv.11.running_var, neck.blocks.0.4.weight, neck.blocks.0.14.weight, bbox_head.tasks.5.conv_box.weight, backbone.middle_conv.21.running_mean, neck.deblocks.1.1.running_mean, backbone.middle_conv.19.bn1.running_var, neck.blocks.0.14.running_mean, backbone.middle_conv.16.weight, backbone.middle_conv.9.bn2.running_mean, backbone.middle_conv.3.conv1.weight, backbone.middle_conv.4.bn1.running_var, backbone.middle_conv.3.bn1.running_var, neck.blocks.1.8.running_mean, bbox_head.tasks.1.conv_dir.bias, backbone.middle_conv.9.bn1.weight, backbone.middle_conv.18.bn1.running_mean, backbone.middle_conv.19.bn1.bias, backbone.middle_conv.14.bn1.running_var, backbone.middle_conv.19.conv2.bias, bbox_head.tasks.5.conv_cls.weight, backbone.middle_conv.3.conv2.bias, backbone.middle_conv.13.bn2.running_mean, backbone.middle_conv.15.weight, neck.blocks.1.13.weight, backbone.middle_conv.13.bn2.running_var, neck.blocks.0.10.weight, neck.blocks.0.8.running_mean, neck.blocks.0.7.weight

**Comment by poodarchu** [comment]
nusc*.py

**Comment by 008yheng** [comment]
thanks i do this, there are some export as above . is right?:
The model and loaded state dict do not match exactly

unexpected key in source state_dict: model, optimizer, iteration, epoch

missing keys in source state_dict

**Comment by 008yheng** [comment]
@poodarchu  thanks for your work ,l  do like this,but when I load your trained model with the file nusc*.py ,the the model unable get right result and the  output as fllow:

The model and loaded state dict do not match exactly

unexpected key in source state_dict: model, optimizer, iteration, epoch

missing keys in source state_dict: backbone.middle_conv.8.bn1.running_var, backbone.middle_conv.3.bn2.running_mean, neck.blocks.0.17.bias, backbone.middle_conv.19.bn2.running_mean, backbone.middle_conv.1.running_mean, bbox_head.tasks.2.conv_dir.weight, backbone.middle_conv.4.conv2.bias, backbone.middle_conv.4.conv1.bias, backbone.middle_conv.11.running_mean, .........

**Comment by poodarchu** [comment]
you can check the loaded checkpoint and see where the mismatch is.

**Comment by zwqnju** [comment]
@poodarchu I think you need to update your code. In your uploaded log file, many layers like "DefaultArgLayer" cannot be found in the current repo. The corresponding config file also needs to be updated. Thanks a lot.

**Comment by poodarchu** [comment]
> @poodarchu I think you need to update your code. In your uploaded log file, many layers like "DefaultArgLayer" cannot be found in the current repo. The corresponding config file also needs to be updated. Thanks a lot.

Indeed, Det3D is refactored for releasing purpose, and the checkpoint is from my earlier codebase.

**Comment by zwqnju** [comment]
Thank you for your reply! @poodarchu Then I hope you can release a checkpoint based on the current Det3D codebase, because the current checkpoint seems hard to use for validation.

**Comment by poodarchu** [comment]
> Thank you for your reply! @poodarchu Then I hope you can release a checkpoint based on the current Det3D codebase, because the current checkpoint seems hard to use for validation.
> 

Can you provide some feedback s?

**Comment by zwqnju** [comment]
I upload a Jupyter Notebook file here: [load checkpoint error](https://github.com/zwqnju/Det3D/blob/master/CBGS.ipynb)

**Comment by tianweiy** [comment]
I can provide some pre-trained models based on a forked version of det3d this week. I fix some bugs and tune the parameters a little bit and get slightly better results. I will create a pull request once I get time.

**Comment by pjohh** [comment]
@tianweiy do you have any results already? I also tried to use the provided checkpoint but it is not possible to use it with this version of Det3D ...

**Comment by tianweiy** [comment]
It will be out with our new paper this week. Please stay tuned

**Comment by tianweiy** [comment]
@pjohh  It will be out with our arxiv paper in the next arxiv cycle (Sunday night in the US, Monday morning in Asia). Thanks for the waiting.

**Comment by pjohh** [comment]
@tianweiy good to hear! Could you please leave a link here when your repo is online?
