### ISSUE TITLE
Where should I update dataset setting and path

### ISSUE THREAD

**Issue by lyirene13** [poodarchu/Det3D#82]
How should I update dataset setting and path? Which configuration file should I edit?

dataset_type = "NuScenesDataset"
n_sweeps = 10
data_root = "/data/Datasets/nuScenes"
db_info_path="/data/Datasets/nuScenes/dbinfos_train.pkl"
train_anno = "/data/Datasets/nuScenes/infos_train_10sweeps_withvelo.pkl"
val_anno = "/data/Datasets/nuScenes/infos_val_10sweeps_withvelo.pkl"

Thank you very much!

**Comment by poodarchu** [comment]
https://github.com/poodarchu/Det3D/blob/master/det3d/datasets/dataset_factory.py
