### ISSUE TITLE
Inference Code for CBGS single point cloud frame(.bin file)

### ISSUE THREAD

**Issue by hz3014** [poodarchu/Det3D#84]
## Feature
Inference Code for CBGS single point cloud frame(.bin file) starting from config file reading and network building. The current code base is not clear for me to write such function. 

## Motivation
The current code base does not inference with single point cloud frame. It would be useful for testing and visualizing desired point cloud frame. 

## Pitch
Config file reader 
Network builder, Target assigner, Voxel Generator
Generate archor
Load Point cloud file
Detection

**Comment by poodarchu** [comment]
you can set nsweeps in config file to 1.
