### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Gang-Chen-China** [poodarchu/Det3D#87]
Hi，yesterday i was traing Poinpillars on nuscenes(v1.0-mimi)，it shows:

**AssertionError: Requested unknown configuration cvpr_2019**
 
maybe the error comes from nuscenes-devkit/eval/detection，do you know how to solve it?

**Comment by poodarchu** [comment]
1. you can use my fork of nuscenes
2. or you can change cvpr_2019 to detection_cvpr_2019 

the corresponding config is here: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/configs/detection_cvpr_2019.json
