### ISSUE TITLE
PointPillars speed

### ISSUE THREAD

**Issue by Nuri-benbarka** [poodarchu/Det3D#89]
I trained PointPillars with the config file you provided on my RTX 2060 GPU and achieved a speed of 21.4Hz. In the publication of PointPillars, they reported a speed of 62Hz on their GTX1080ti which should be ~50% faster than mine, so I was expecting a speed aroand 40Hz. In general, is there a speed loss when using this framework?

![Screenshot from 2020-03-26 12-41-18](https://user-images.githubusercontent.com/60135952/77643216-43e6d900-6f5f-11ea-9a9a-9e27390ad9d8.png)

**Comment by poodarchu** [comment]
I think they only take forward time into consideration. but infact there're also data preparation and post processing time.

**Comment by jhultman** [comment]
Hi @Nuri-benbarka, the PointPillars authors used TensorRT to reach 62 hz (42 hz without TensorRT), including all pre- and postprocessing.

![tensorrt](https://user-images.githubusercontent.com/27909223/78608974-c7da7400-782f-11ea-914c-d6765c7cd122.png)

**Comment by Nuri-benbarka** [comment]
Many thanks, @jhultman. Now the runtimes make sense to me.
