### ISSUE TITLE
Wrong computation of f_center in PillarFeatureNet

### ISSUE THREAD

**Issue by zwqnju** [poodarchu/Det3D#92]
In https://github.com/poodarchu/Det3D/blob/b4cb6428b807d8cfe2135b535961d710ff9d41c1/det3d/models/readers/pillar_encoder.py#L129
it is to compute the x distance between each point and its corresponding pillar's center. But the current code does not use the point's x value.
This line should be modified to: `f_center[:, :, 0] = features[:, :, 0] - (`
The computation in y axis has the similar bug, and should be modified too:
https://github.com/poodarchu/Det3D/blob/b4cb6428b807d8cfe2135b535961d710ff9d41c1/det3d/models/readers/pillar_encoder.py#L132

#68 also mentioned this issue.

**Comment by tianweiy** [comment]
@zwqnju this is a bug. Besides, [here](https://github.com/poodarchu/Det3D/blob/b4cb6428b807d8cfe2135b535961d710ff9d41c1/det3d/models/readers/pillar_encoder.py#L120) is also incorrect for pointpillar on nuScene. Basically, the timestamp for different sweeps is discarded

**Comment by zwqnju** [comment]
@tianweiy Oh, I see. Thanks. I also found another bug: 
In [the construction method of PillarFeatureNet](https://github.com/poodarchu/Det3D/blob/b4cb6428b807d8cfe2135b535961d710ff9d41c1/det3d/models/readers/pillar_encoder.py#L61),  `voxel_size` and `pc_range` both have default values. In the config file like [this](https://github.com/poodarchu/Det3D/blob/b4cb6428b807d8cfe2135b535961d710ff9d41c1/examples/point_pillars/configs/nusc_all_point_pillars_mghead_syncbn.py#L137), the `voxel_size` and `pc_range` are different with the default values, but the config file do not set them explicitly in model.reader. This also results in the wrong computation of f_center.

**Comment by tianweiy** [comment]
@zwqnju  Great, thanks. Besides, I feel the directional classifier is definitely incorrect for nuscene. And the db sampling / GT Aug for nuScene seems to have some bug but I haven't got time to look into it... (e.g. it seems to also assume the center is at the bottom of the box like KITTI)

**Comment by poodarchu** [comment]
you can make a mr.
