### ISSUE TITLE
When I use the kitti dataset, I cannot find the planes folder. What is the planes folder?

### ISSUE THREAD

**Issue by XiaomuWang** [poodarchu/Det3D#93]
with open(plane_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wangsen/data/Datasets/KITTI/data_object_velodyne/training/planes/003414.txt'

**Comment by poodarchu** [comment]
Out of the scope of Det3D. Please refer to KITTI website for help.
