### ISSUE TITLE
When I run the code on the kitti dataset, I found a bug .

### ISSUE THREAD

**Issue by XiaomuWang** [poodarchu/Det3D#94]
When I run the code on the kitti dataset, I found a bug and could not find the plane file. This is the case in the code.
        <self.plane_dir = "/data/Datasets/KITTI/Kitti/object/training/planes">
But the kitti dataset does not have this folder.And I haven't seen this written in other target detection algorithms.

**Comment by XiaomuWang** [comment]
The error is as follows：
FileNotFoundError: [Errno 2] No such file or directory: '/data/Datasets/KITTI/Kitti/object/training/planes/003529.txt'

**Comment by XiaomuWang** [comment]
The above code is in ./det3d/dataset/kitti/kitti.py

**Comment by poodarchu** [comment]
If you do not have planes files, you can manually remove related codes, or download the plane files.
