### ISSUE TITLE
Anchor generator

### ISSUE THREAD

**Issue by jinglin80** [poodarchu/Det3D#98]
Hi, 

May I know how did you get these values? Any source link?

Following code is from https://github.com/poodarchu/Det3D/blob/master/GETTING_STARTED.md

      anchor_generators=[
    dict(
        type="anchor_generator_range",
        sizes=[1.97, 4.63, 1.74],
        anchor_ranges=[-50.4, -50.4, -0.95, 50.4, 50.4, -0.95],
        rotations=[0, 1.57],
        velocities=[0, 0],
        matched_threshold=0.6,
        unmatched_threshold=0.45,
        class_name="car",
    ),
    dict(
        type="anchor_generator_range",
        sizes=[2.51, 6.93, 2.84],
        anchor_ranges=[-50.4, -50.4, -0.40, 50.4, 50.4, -0.40],
        rotations=[0, 1.57],
        velocities=[0, 0],
        matched_threshold=0.55,
        unmatched_threshold=0.4,
        class_name="truck",
    ),
    ...
Thanks,
Jing

**Comment by poodarchu** [comment]
statistics

**Comment by jinglin80** [comment]
May I know which branch of statistics are you referring to? May you give me a little bit for information?

Thank you very much for time and clarification,
Jing

**Comment by poodarchu** [comment]
You can count the length, width, and height of different types of objects.
